name: Pytest

on: [push]

jobs:
  build:

    runs-on: linux-latest
    strategy:
      matrix:
        python-version: [3.5.9, 3.8.6, 3.9.9, 3.10.0]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
